### ISSUE TITLE
Hi, is there any missing txt file related to the Urb3dcd data set?

### ISSUE THREAD

**Issue by ZZH86** [wangle53/3DCDNet-Urb3DCD#1]
**I got the following error when I tried to run**

`(new_3dcd_1) ch@Server:/mnt/data/ch/code/3DCDNet-Urb3DCD-main$ python test.py
***generating training val and test data from Ubr3DCD dataset, it will take some time.***
   1. projecting label {removed: 2} from point cloud 2 into point cloud 1......
   2. cropping Pcs......
   3. write train val and test .txt files......
***data preparation finished***
Traceback (most recent call last):
  File "test.py", line 85, in <module>
    test_network(tcfg)
  File "test.py", line 22, in test_network
    test_data = CDDataset(tcfg.path['test_dataset_path'], tcfg.path['test_txt'], tcfg.n_samples, 'test', tcfg.path.prepare_data)
  File "/mnt/data/ch/code/3DCDNet-Urb3DCD-main/dataset.py", line 49, in __init__
    prepare_data()
  File "/mnt/data/ch/code/3DCDNet-Urb3DCD-main/dataset_utils/process_data2accelerate.py", line 132, in prepare_data
    pptrain = PrepareData(tcfg.train_flag, tcfg.path['train_dataset_path'], tcfg.path['train_txt'], tcfg.n_samples)
  File "/mnt/data/ch/code/3DCDNet-Urb3DCD-main/dataset_utils/process_data2accelerate.py", line 48, in __init__
    with open(self.txt_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data_50_50/1-Lidar05/TrainNormal-1b.txt'`

**Comment by wangle53** [comment]
I have uploaded the '.txt' files. Please you can download the files to your path. Thanks for your interest.

**Comment by LegionHXF** [comment]
> **I got the following error when I tried to run**
> 
> `(new_3dcd_1) ch@Server:/mnt/data/ch/code/3DCDNet-Urb3DCD-main$ python test.py _**generating training val and test data from Ubr3DCD dataset, it will take some time.**_
> 
> 1. projecting label {removed: 2} from point cloud 2 into point cloud 1......
> 2. cropping Pcs......
> 3. write train val and test .txt files......
>    _**data preparation finished**_
>    Traceback (most recent call last):
>    File "test.py", line 85, in 
>    test_network(tcfg)
>    File "test.py", line 22, in test_network
>    test_data = CDDataset(tcfg.path['test_dataset_path'], tcfg.path['test_txt'], tcfg.n_samples, 'test', tcfg.path.prepare_data)
>    File "/mnt/data/ch/code/3DCDNet-Urb3DCD-main/dataset.py", line 49, in **init**
>    prepare_data()
>    File "/mnt/data/ch/code/3DCDNet-Urb3DCD-main/dataset_utils/process_data2accelerate.py", line 132, in prepare_data
>    pptrain = PrepareData(tcfg.train_flag, tcfg.path['train_dataset_path'], tcfg.path['train_txt'], tcfg.n_samples)
>    File "/mnt/data/ch/code/3DCDNet-Urb3DCD-main/dataset_utils/process_data2accelerate.py", line 48, in **init**
>    with open(self.txt_path, 'r') as f:
>    FileNotFoundError: [Errno 2] No such file or directory: './data_50_50/1-Lidar05/TrainNormal-1b.txt'`

Hello, I would like to ask if this code can be reproduced successfully?

**Comment by wangle53** [comment]
Yes, this code can be reproduced successfully.
